/**
 * 權限配置檔
 * 定義系統中所有的權限和角色權限映射
 */

// 基礎權限定義
export const PERMISSIONS = {
  // 系統管理權限
  MANAGE_SYSTEM: 'manage_system',
  MANAGE_BRANDS: 'manage_brands',
  MANAGE_SYSTEM_ADMINS: 'manage_system_admins',

  // 品牌管理權限
  MANAGE_BRAND: 'manage_brand',
  MANAGE_STORES: 'manage_stores',
  MANAGE_BRAND_ADMINS: 'manage_brand_admins',

  // 店鋪管理權限
  MANAGE_STORE: 'manage_store',
  MANAGE_STORE_ADMINS: 'manage_store_admins',

  // 業務操作權限
  ORDER_SYSTEM: 'order_system',
  VIEW_REPORTS: 'view_reports',
  EDIT_BACKEND: 'edit_backend',
  MANAGE_INVENTORY: 'manage_inventory',
  MANAGE_MENU: 'manage_menu',
  MANAGE_CUSTOMERS: 'manage_customers',
  MANAGE_ORDERS: 'manage_orders',
  MANAGE_PROMOTIONS: 'manage_promotions'
};

// 角色權限映射
export const ROLE_PERMISSIONS = {
  primary_system_admin: [
    PERMISSIONS.MANAGE_SYSTEM,
    PERMISSIONS.MANAGE_BRANDS,
    PERMISSIONS.MANAGE_SYSTEM_ADMINS,
    PERMISSIONS.MANAGE_BRAND,
    PERMISSIONS.MANAGE_STORES,
    PERMISSIONS.MANAGE_BRAND_ADMINS,
    PERMISSIONS.MANAGE_STORE,
    PERMISSIONS.MANAGE_STORE_ADMINS,
    PERMISSIONS.ORDER_SYSTEM,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EDIT_BACKEND,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_PROMOTIONS
  ],
  system_admin: [
    PERMISSIONS.MANAGE_BRANDS,
    PERMISSIONS.MANAGE_BRAND,
    PERMISSIONS.MANAGE_STORES,
    PERMISSIONS.MANAGE_STORE,
    PERMISSIONS.ORDER_SYSTEM,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EDIT_BACKEND,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_PROMOTIONS
  ],
  primary_brand_admin: [
    PERMISSIONS.MANAGE_BRAND,
    PERMISSIONS.MANAGE_STORES,
    PERMISSIONS.MANAGE_BRAND_ADMINS,
    PERMISSIONS.MANAGE_STORE,
    PERMISSIONS.MANAGE_STORE_ADMINS,
    PERMISSIONS.ORDER_SYSTEM,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EDIT_BACKEND,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_PROMOTIONS
  ],
  brand_admin: [
    PERMISSIONS.MANAGE_BRAND,
    PERMISSIONS.MANAGE_STORES,
    PERMISSIONS.MANAGE_STORE,
    PERMISSIONS.ORDER_SYSTEM,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EDIT_BACKEND,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_PROMOTIONS
  ],
  primary_store_admin: [
    PERMISSIONS.MANAGE_STORE,
    PERMISSIONS.MANAGE_STORE_ADMINS,
    PERMISSIONS.ORDER_SYSTEM,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EDIT_BACKEND,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_PROMOTIONS
  ],
  store_admin: [
    PERMISSIONS.ORDER_SYSTEM,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EDIT_BACKEND,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_PROMOTIONS
  ],
  employee: [
    PERMISSIONS.ORDER_SYSTEM,
    PERMISSIONS.MANAGE_INVENTORY
  ]
};

// 角色層級定義
export const ROLE_LEVELS = {
  primary_system_admin: 7,
  system_admin: 6,
  primary_brand_admin: 5,
  brand_admin: 4,
  primary_store_admin: 3,
  store_admin: 2,
  employee: 1
};

// 角色範圍定義
export const ROLE_SCOPES = {
  primary_system_admin: 'system',
  system_admin: 'system',
  primary_brand_admin: 'brand',
  brand_admin: 'brand',
  primary_store_admin: 'store',
  store_admin: 'store',
  employee: 'store'
};

// 權限描述
export const PERMISSION_DESCRIPTIONS = {
  [PERMISSIONS.MANAGE_SYSTEM]: '系統管理',
  [PERMISSIONS.MANAGE_BRANDS]: '品牌管理',
  [PERMISSIONS.MANAGE_SYSTEM_ADMINS]: '系統管理員管理',
  [PERMISSIONS.MANAGE_BRAND]: '品牌設定管理',
  [PERMISSIONS.MANAGE_STORES]: '店鋪管理',
  [PERMISSIONS.MANAGE_BRAND_ADMINS]: '品牌管理員管理',
  [PERMISSIONS.MANAGE_STORE]: '店鋪設定管理',
  [PERMISSIONS.MANAGE_STORE_ADMINS]: '店鋪管理員管理',
  [PERMISSIONS.ORDER_SYSTEM]: '訂單系統操作',
  [PERMISSIONS.VIEW_REPORTS]: '查看報表',
  [PERMISSIONS.EDIT_BACKEND]: '編輯後台資料',
  [PERMISSIONS.MANAGE_INVENTORY]: '庫存管理',
  [PERMISSIONS.MANAGE_MENU]: '菜單管理',
  [PERMISSIONS.MANAGE_CUSTOMERS]: '客戶管理',
  [PERMISSIONS.MANAGE_ORDERS]: '訂單管理',
  [PERMISSIONS.MANAGE_PROMOTIONS]: '促銷管理'
};
